name: workflow to Execute the Python application
on:
 workflow_dispatch:
 push:
   branches:
        - master
 pull_request:
   branches:
        - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: Clone the repo
       uses: actions/checkout@v6
     - name: Install the python application
       uses: actions/setup-python@v6
       with:
        python-version: '3.13'
     - name: Install the python dependencies
       run:
        pip install --upgrade pip
        pip install -r requirements.txt   
     - name: set PythonPATH
       run: echo "PYTHONPATH"=$GITHUB_WORKSPACE >> $GITHUB_ENV
     - name: Run tests
       run: pytest tests --cov=app --cov-report=xml
